version: '3.8'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: "./Backend"
    ports: 
      - "3001:3001"  
    volumes:
      - /app/node_modules
      - ./Backend:/app

  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./Frontend
    volumes:
      - /app/node_modules
      - ./Frontend:/app